# -*- coding: utf-8 -*-
"""
[游戏模块 nuli_slave] 奴隶买卖 文本库 — 抽离自 slave.py v0.43
原文逐字提取自 nuli4.2.dll (小栗子版)
"""
EVENT_MASTER_UP  = "【奇遇】{text}\r\n主人货币 +{amt}"
EVENT_MASTER_DOWN= "【奇遇】{text}\r\n主人货币 -{amt}"
EVENT_SLAVE_UP   = "【奇遇】{text}\r\n奴隶货币 +{amt}"
EVENT_SLAVE_DOWN = "【奇遇】{text}\r\n奴隶货币 -{amt}"

MENU = (
    "🏰 奴隶买卖系统\r\n"
    "━━━━━━━━━━━━━━\r\n"
    "💼 奴隶打工　　🎒 奴隶收工\r\n"
    "🙏 讨好主人　　⚡ 折磨奴隶\r\n"
    "📚 我要学习　　⛩️ 我要祈福\r\n"
    "🕊️ 我要自由　　⚔️ 我要造反\r\n"
    "👤 我的信息\r\n"
    "🗡️ 武器菜单　　🎁 宝物菜单\r\n"
    "🎰 抽武器/十连抽/三十连抽/五十连抽　升星/升阶\r\n"
    "🛒 买下@QQ　　🕊️ 释放@QQ\r\n"
    "💰 赎身@QQ　　🛡️ 保护@QQ\r\n"
    "⚔️ 打架@QQ\r\n"
    "🔍 查询@QQ\r\n"
    "📦 买奴隶位\r\n"
    "━━━━━━━━━━━━━━\r\n"
    "🏆 身价排行榜　　📅 签到排行榜\r\n"
    "📊 排行榜（财富/签到/体力/发言）\r\n"
    "━━━━━━━━━━━━━━\r\n"
    "💡 发送对应指令即可游玩"
)

NOT_IN_GROUP   = "Ta不是本群的小伙伴，无法操作！"
BOT_NO_JOIN    = "机器人是不参加游戏的！"
BOT_NO_TRADE   = "机器人是不可以被买卖的！"
SELF_OP_WEIRD  = "啊这~亲这么厉害自己给自己当奴隶的嘛?"
SELF_FIGHT     = "这是什么操作！？居然可以自己释放自己的吗！？"
SELF_RELEASE   = "这是什么操作！？居然可以自己释放自己的吗！？"
SELF_BUY_SELF  = "你想买你的主人！？赶紧醒醒！把药吃了~"
POOR           = "笑~你没有那么多{coin}"
NOT_ENOUGH     = "不足，攒够了再来吧~"
COOLDOWN_MIN   = "{min}分钟再来{act}吧！"
REPEAT_ACT     = "你刚刚已经{act}过了！"

QUERY_WHO      = "你要查询谁？请正确的@他"
PROTECT_WHO    = "你要保护谁？请输入正确的@他"
BUY_WHO        = "你要买下谁？请输入正确的@他"
TORTURE_WHO    = "你要折磨谁？请输入正确的@他"
FIGHT_WHO      = "你要和谁打架？请输入正确的@他"
RELEASE_WHO    = "你要释放谁？请输入正确的@他"
RANSOM_WHO     = "你要为谁赎身？请输入正确的@他，为自己赎身请输入【我要自由】"
NO_OWNER       = "木有主人"
NO_SLAVE       = "木有奴隶"
NO_TREASURE    = "木有宝物"
NO_WEAPON      = "木有武器"
NO_PROTECT     = "无人保护"

ALREADY_PROTECTED_BY_YOU = "正在被你保护着呢，剩余保护时间{min}分钟！"
PROTECT_POOR             = "笑~亲没有那么多{coin}\r\n哦~保护"
PROTECTED_CANNOT_BUY     = "{min}分钟内无法被其他人买走！"
PROTECT_OK               = "恭喜您花费{cost}{coin}保护{who}，剩余保护时间{min}分钟！"
PROTECT_NOT_YOURS        = "Ta不是你的奴隶，你无法保护Ta"

BUY_IS_MINE      = "Ta已经是你的奴隶啦，无需再买！"
BUY_SLOT_FULL    = "你当前最多只能有{cap}个奴隶，请发送[买奴隶位]购买更多位置。"
BUY_PROTECTED    = "Ta正被{who}保护中，请等待{min}分钟再来买下"
BUY_JUST_TRADED  = "{min}分钟前刚刚被交易过，正在恢复情绪中！"
BUY_OK_HEAD      = "成功买下{who}"
BUY_COST         = "本次买入花费：{cost}"
BUY_PRICE_UP     = "奴隶身价上涨：{up}"
BUY_PRICE_NOW    = "奴隶现在身价：{now}"
BUY_PREV_OWNER   = "奴隶上任主人：{prev}"
BUY_PREV_COST    = "原主买入价格：{orig}"
BUY_PREV_PROFIT  = "原主获取利润：{profit}"

TORTURE_SELF     = "你真厉害,自已折磨自己很舒服对不对？"
TORTURE_NOT_MINE = "对方还不是你的奴隶哦,想折磨就要先买下才行哦~"
TORTURE_CD       = "{min}分钟再去折磨"
TORTURE_JUST     = "Ta刚刚被你折磨过，你要折磨死Ta吗！？"
TORTURE_MERCY    = "你的奴隶用眼含热泪的眼神乞求你饶了Ta，你放弃了折磨！"
TORTURE_ALL_DONE = "您的奴隶已经全部折磨完毕，请勿重复折磨！"

FIGHT_MASTER     = "你想跟你的主人打架！？小心被折磨哦~"
FIGHT_NO_SLAVE   = "你都没有奴隶，难道你要自己上阵打架？"
FIGHT_OWN_SLAVE  = "你要带着你的奴隶打你自己的奴隶？！我的天！"
FIGHT_ENEMY_NO_S = "对方没有奴隶，你好意思带着一群奴隶小弟群殴他吗？"
FIGHT_HEAD       = "打架啦！"
FIGHT_CALL_UP    = "开始召集你的奴隶们和{who}的奴隶们决斗！"
FIGHT_MY_TEAM    = "我方派出奴隶：{team}"
FIGHT_CRIT       = "触发武器技能狂热，本次战力翻倍！"
FIGHT_ENEMY_TEAM = "对方派出奴隶：{team}"
FIGHT_TOO_STRONG = "算啦算啦~你的战斗力强Ta太多啦，欺负弱小多没意思吖~"
FIGHT_POWER_CMP  = "双方战力对比：{a} VS {b}"
FIGHT_I_AM_POOR  = "@你的财产太少了，对方担心你输不起不屑与你打架！"
FIGHT_TA_IS_POOR = "对方财产太少了，无力支付战斗失败后的赔款，可怜可怜Ta吧~"
FIGHT_WINRATE    = "此次战斗胜率：{pct}%(胜率越高赢面越大,但不保证一定会胜利哦~)"
FIGHT_WIN        = "?本次战斗结果：胜利！"
FIGHT_GET_MONEY  = "获得对方赔款：{money}"
FIGHT_MASTER_BACK= "对方把你的主人赔偿给你，你一看是自己主人，吓得赶紧释放了！"
FIGHT_GET_SLAVE  = "获得对方奴隶：{slave}"
FIGHT_SLOT_FULL  = "奴隶已达上限：收取赎金{money}"
FIGHT_TA_SHIELD  = ",引的霞光万道，如金钟罩一般死死护住奴隶,您只好悻悻而去~"
FIGHT_TA_TREASURE= "您向对面索要赔偿的奴隶,不料Ta掏出了宝物"
FIGHT_LOSE       = "本次战斗结果：失败！"
FIGHT_PAY_MONEY  = "对方获得赔款：{money}"
FIGHT_PAY_SLAVE  = "你把Ta的主人赔给了Ta，Ta的主人把Ta暴打了顿，扬长而去！"
FIGHT_LOSE_SLAVE = "对方获得奴隶：{slave}"
FIGHT_MY_SHIELD  = ",引的霞光万道，如金钟罩一般死死护住奴隶,Ta只好悻悻而去~"
FIGHT_MY_TREASURE= "对方向您索要赔偿的奴隶,不料您掏出了宝物"
FIGHT_CD         = "{min}分钟再与人打架吧！"
FIGHT_RESTING    = "啊这！奴隶们正在恢复体力，请等待{min}分钟"

RELEASE_OK       = "恭喜你，成功释放{who}，Ta已恢复自由！"
RANSOM_NO_OWNER  = "你没有主人啊！跟空气赎身吗？"
RANSOM_TA_FREE   = "Ta没有主人啊！你跟谁赎身！？"
RANSOM_OWN_SLAVE = "你要帮自己的奴隶赎身么？！直接释放就可以了"
RANSOM_CD        = "{min}分钟再来给Ta赎身吧！"
FREE_CD          = "{min}分钟再来换取自由吧！"
FREE_EVIL_MASTER = "万恶的主人"
FREE_BY_TORTURE  = "不堪主人折磨，花费{cost}"
FREE_KIND        = "大发善心，花费{cost}"
FREE_FAIL_PAY    = "交给你的主人，无法恢复自由！"

T_NAME           = "宝物名称：{name}"
T_EFFECT         = "宝物效果：{effect}"
T_STAGE          = "【{n}阶】"
T_GOURD_EFFECT   = "灌醉您的奴隶,极大的增加其造反难度"
T_CHARM_EFFECT   = "打架失败时降低赔偿奴隶的概率"
T_COMMON_EFFECT  = "镇宅纳福的收藏宝物，升阶可提升其收藏价值"
TUP_NOT_EXIST    = "你输入的宝物名称不存在，请输入正确格式：【升阶+宝物名称】 或输入【宝物菜单】即可查看当前宝物种类哦"
TUP_NO_ITEM      = "数量不够哦，攒够了再来吧~"
TUP_NO_COIN      = "哦，攒够了再来吧~"
TUP_FAIL         = "脸黑了亿点呢,本次升阶未成功哦,请再接再厉吧~"
TUP_USED         = "本次升阶消耗宝物：{items}"
TUP_COST         = "本次升阶花费：{cost}"
TUP_PROB         = "本次升阶概率：{prob}%"
TUP_FAIL_KEEP    = "，宝物不会消失哦~"
TUP_FAIL_ONLY    = "升阶失败只扣除{part}"
TUP_MAX          = "已升到3阶，属性值已达到最高，不需要再升阶了哦~"
TUP_NO_PERM      = "哦，是不可以进行这项操作的~"
TUP_HAVE_NONE    = "你还没有宝物哦，是不可以进行这项操作的~"

W_NAME           = "武器名称：【{name}】"
W_EFFECT         = "武器效果：战斗力 {atk}"
W_5STAR_EFFECT   = "5星特效：主动打架概率触发狂热，该次总战力翻倍，每有一把5星武器概率均可累计增加10%（被动打架不触发）"
WUP_NOT_EXIST    = "你输入的武器名称不存在，请输入正确格式：【升星+武器名称】 或输入【武器菜单】即可查询当前武器种类哦~"
WUP_NO_EXP       = "你的武器经验不足哦，攒够了再来吧~"
WUP_FAIL         = "脸黑了亿点呢，本次升星未成功哦，请再接再厉吧~"
WUP_USE_WEAPON   = "本次升星消耗武器：{items}"
WUP_USE_EXP      = "本次升星消耗经验：{exp}"
WUP_USE_COIN     = "本次升星花费：{coin}"
WUP_PROB         = "本次升星概率：{prob}%，武器不会消失哦~"
WUP_FAIL_LOSS    = "升星失败只扣除经验和{items}"
WUP_OK           = "成功升星{name}"
WUP_MAX          = "已升到5星,属性值已达到最高,不需要再升星了哦~"
WUP_HAVE_NONE    = "你还没有武器哦，是不可以进行这项操作的~"

GACHA_EXP_GAIN   = "获得武器经验：{exp}"
GACHA_COST_NOTE  = "本次抽武器消耗{coin}"
GACHA_RULE       = "抽到的 R/SR 直接转化为武器经验，抽到的 SSR 数量达到上限后转化为武器经验"
GACHA_EXP_CONV   = "经验转化： R:{r} SR:{sr}"
GACHA_TEN_HEAD   = "武器十连抽需要消耗{coin}"
GACHA_NO_SSR     = "被衰神附体，与SSR擦身而过~"
GACHA_TOTAL_EXP  = "累计获得武器经验：{exp}"
GACHA_TEN_CONV   = "转化经验： R:{r} SR:{sr}"

REVOLT_NO_OWNER  = "你没有主人啊，跟空气造反吗！？"
REVOLT_CD        = "{min}分钟再进行造反吧！"
REVOLT_DONE      = "你刚刚已经造反过了！"
REVOLT_FAIL_STAY = "！你还是安心当奴隶吧！~"
REVOLT_TOO_POOR  = "你太穷了，连反抗的资格都没有！至少需要{need}"
REVOLT_CRUSHED   = "你主人奴隶比你多一倍，你无力抗争，造反被其他奴隶镇压了！你还可以花钱赎身！"
REVOLT_POOR_MASTER = "因你的主人实在太穷了，他无力与你斗争，恭喜你恢复自由啦！"
REVOLT_FREE      = "，并恢复自由！"
RV_LOOT          = "抢走主人{loot}{coin}"
RV_GOURD_WIN     = "【酒神葫芦】的醉人酒香,把已经喝到人事不醒的主人扔到路边"
RV_GOURD_LOSE    = "主人智商通神早发现你有二心,取出竹叶寨神器【酒神葫芦】一通猛倒,导致你被灌醉从而无法逃脱,被迫上缴给主人"
RV_NORMAL_WIN    = "经过艰苦卓绝的战斗，你打败了万恶的主人"
RV_NORMAL_LOSE   = "你没能逃脱主人的折磨，被主人暴打一顿后,上缴给主人"
RV_RESIST_GOURD  = "经过艰苦卓绝的拼斗，你抵住了"

STUDY_NO_OWNER   = "你没有主人，没人帮你支付学费吖！"
STUDY_CD         = "{min}分钟再来学习吧！"
STUDY_DONE       = "你刚刚已经学习过了，休息下吧！"
STUDY_POOR_MASTER= "你的主人太穷了，支付不起你的学费，你的学费需要：{fee}"
STUDY_QUIT       = "发现学习太辛苦，放弃了学习！"

WORK_NO_SLAVE    = "你还没有奴隶为你赚钱，赶紧买奴隶吧！"
WORK_NOT_FINISH  = "你的奴隶们上一份工作已经完成了，请先让他们收工吧！"
WORK_DISPATCH    = "开始派遣你的奴隶们出门打工啦！\r\n赚取目标：{target}\r\n请耐心等待您的奴隶们打工完成，预计需要{min}分钟可以收工！"
WORK_WORKING     = "你的奴隶们正在努力为你打工中，预计{min}分钟可以收工！"
WORK_NOT_STARTED = "你的奴隶还没有开始打工呢！"
WORK_COLLECT     = "你的奴隶们打工完成，本次预计所得：{total}"
WORK_NO_WAGE     = "，奴隶身价太低主人没发工资"
WORK_GOT_WAGE    = "，获得主人发放工资{wage}"
WORK_WAGE_TOTAL  = "发放工资合计：{wage}"
WORK_MASTER_GET  = "主人实际所得{got}"
WORK_CD          = "{min}分钟再来收工！"
WORK_WAIT        = "你的奴隶们还没有到收工时间，请等待{min}分钟"

FLATTER_NO_OWNER = "你没有主人，没有办法进行讨好！"
FLATTER_CD       = "{min}分钟再来讨好主人吧！"
FLATTER_DONE     = "你刚刚讨好过主人，主人拒绝了你的讨好！"
FLATTER_RICHER   = "你的主人身价还没有你高，你好意思问他要钱吗？"
FLATTER_POOR_M   = "真可怜，跟了个穷鬼主人，主人摸了摸口袋什么都没有！"
FLATTER_OK       = "摇摇尾巴~向你主人卖个萌，主人一开心给了你{got}"

SLOT_SYS_MAX     = "抱歉，你的奴隶位已达系统上限，无法购买"
SLOT_BUY_ONE     = "买下一个奴隶位。"
SLOT_NOW_CAP     = "当前可拥有奴隶上限：{cap}"
SLOT_NEXT_PRICE  = "下次购买奴隶位价格：{price}"
SLOT_NEED        = "哦，购买奴隶位需要{price}"
SLOT_POOR        = "笑~你没有那么多{coin}"

PRAY_TIME_NOTYET = "时间未到,还不可以祭拜忍神哦,该活动每天中午12点整开启~\r\n请等待一下吧！"
PRAY_BIG         = "天呐,这一次人品大爆发,忍神在天堂听到了呼唤,大大赏赐了{amt}"
PRAY_PITY_HEAD   = "笑~忍神大人在天堂里一手臭牌正频频点炮,忽听得有人祭拜,正好正好,送点钱过来好翻本~可怜的{who}"
PRAY_NORMAL      = "笑~忍神大人心情不错,看着面前楚楚可怜的{who},一高兴赏了{amt}"
PRAY_NINJA       = "笑~忍神大人心情不错,对忍村后代很满意,一高兴赏了{amt}"

SWITCH_STATE     = "奴隶买卖已{state}"
SWITCH_NO_PERM   = "你没有权限控制奴隶买卖开关。"
